apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-[SERVICE_NAME]
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: secret-store-[ENV]
    kind: SecretStore
  target:
    name: env-[SERVICE_NAME]
  dataFrom:
  - extract:
      key: [SERVICE_NAME]
