apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: [SERVICE_NAME]-hpa
  namespace : default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: [SERVICE_NAME]
  minReplicas: 2
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
