apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 60s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: SecretStore
    name: vault-backend               # name of the SecretStore (or kind specified)
  target:
    name: secret-to-be-created  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: beta/live-mobile-web  # name of the GCPSM secret
