apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "1s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: test-sync
  dataFrom:
  - extract:
      key: test
